/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TaskReminderPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian11 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  enabled: true,
  popupDelay: 3e4,
  popupDuration: 8e3,
  reminderStyle: "both",
  showStatusBar: true,
  taskSources: {
    daily: true,
    nike: true,
    holiday: true,
    recurring: true
  },
  dailyNotePath: "",
  nikePath: "",
  recurringConfigPath: "",
  lastReminderDate: "",
  confirmBeforeMove: true,
  allowMoveToPast: false,
  dailyNoteTemplatePath: ""
};
var FolderSuggest = class extends import_obsidian.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(inputStr) {
    const abstractFiles = this.app.vault.getAllLoadedFiles();
    const folders = [];
    const lowerCaseInputStr = inputStr.toLowerCase();
    abstractFiles.forEach((folder) => {
      if (folder instanceof import_obsidian.TFolder && folder.path.toLowerCase().includes(lowerCaseInputStr)) {
        folders.push(folder);
      }
    });
    return folders.sort((a, b) => a.path.length - b.path.length).slice(0, 20);
  }
  renderSuggestion(folder, el) {
    el.createEl("div", { text: folder.path, cls: "suggestion-content" });
  }
  selectSuggestion(folder) {
    this.inputEl.value = folder.path;
    this.inputEl.trigger("input");
    this.close();
  }
};
var FileSuggest = class extends import_obsidian.AbstractInputSuggest {
  constructor(app, inputEl, extension = "md") {
    super(app, inputEl);
    this.inputEl = inputEl;
    this.extension = extension;
  }
  getSuggestions(inputStr) {
    const abstractFiles = this.app.vault.getAllLoadedFiles();
    const files = [];
    const lowerCaseInputStr = inputStr.toLowerCase();
    abstractFiles.forEach((file) => {
      if (file instanceof import_obsidian.TFile && file.extension === this.extension && file.path.toLowerCase().includes(lowerCaseInputStr)) {
        files.push(file);
      }
    });
    return files.sort((a, b) => a.path.length - b.path.length).slice(0, 20);
  }
  renderSuggestion(file, el) {
    el.createEl("div", { text: file.path, cls: "suggestion-content" });
  }
  selectSuggestion(file) {
    this.inputEl.value = file.path;
    this.inputEl.trigger("input");
    this.close();
  }
};
var TaskReminderSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    var _a, _b, _c;
    const { containerEl } = this;
    containerEl.empty();
    const dvApi = (_c = (_b = (_a = this.app.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b.dataview) == null ? void 0 : _c.api;
    if (!dvApi) {
      const warningEl = containerEl.createDiv({ cls: "task-reminder-warning" });
      warningEl.createEl("p", {
        text: "\u26A0\uFE0F \u9700\u8981\u5B89\u88C5\u5E76\u542F\u7528 Dataview \u63D2\u4EF6",
        cls: "mod-warning"
      });
      const linkEl = warningEl.createEl("a", {
        text: "\u67E5\u770B\u5B89\u88C5\u6307\u5357",
        href: "https://github.com/blacksmithgu/obsidian-dataview"
      });
      linkEl.setAttr("target", "_blank");
    }
    containerEl.createEl("h2", { text: "\u57FA\u7840\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u542F\u7528\u81EA\u52A8\u63D0\u9192").setDesc("Obsidian \u542F\u52A8\u65F6\u81EA\u52A8\u663E\u793A\u4ECA\u65E5\u4EFB\u52A1\u63D0\u9192").addToggle((toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
      this.plugin.settings.enabled = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u5EF6\u8FDF\u65F6\u95F4\uFF08\u79D2\uFF09").setDesc("\u542F\u52A8\u540E\u7B49\u5F85\u591A\u5C11\u79D2\u518D\u5F39\u7A97\uFF08\u5EFA\u8BAE\u7B49\u5F85\u540C\u6B65\u5B8C\u6210\uFF09").addSlider((slider) => slider.setLimits(5, 120, 5).setValue(this.plugin.settings.popupDelay / 1e3).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.popupDelay = value * 1e3;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u901A\u77E5\u663E\u793A\u65F6\u957F\uFF08\u79D2\uFF09").setDesc("Notice \u901A\u77E5\u5728\u5C4F\u5E55\u4E0A\u663E\u793A\u7684\u65F6\u95F4").addSlider((slider) => slider.setLimits(3, 30, 1).setValue(this.plugin.settings.popupDuration / 1e3).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.popupDuration = value * 1e3;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u63D0\u9192\u6837\u5F0F").setDesc("\u9009\u62E9\u63D0\u9192\u7684\u663E\u793A\u65B9\u5F0F").addDropdown((dropdown) => dropdown.addOption("both", "\u4E24\u8005\u90FD\u663E\u793A").addOption("notice", "\u4EC5\u901A\u77E5\u680F").addOption("modal", "\u4EC5\u5F39\u7A97").setValue(this.plugin.settings.reminderStyle).onChange(async (value) => {
      this.plugin.settings.reminderStyle = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u663E\u793A\u72B6\u6001\u680F\u6307\u793A\u5668").setDesc("\u5728\u72B6\u6001\u680F\u663E\u793A\u4ECA\u65E5\u5F85\u529E\u6570\u91CF").addToggle((toggle) => toggle.setValue(this.plugin.settings.showStatusBar).onChange(async (value) => {
      this.plugin.settings.showStatusBar = value;
      await this.plugin.saveSettings();
      new import_obsidian.Notice("\u9700\u8981\u91CD\u542F Obsidian \u4EE5\u5E94\u7528\u72B6\u6001\u680F\u8BBE\u7F6E");
    }));
    containerEl.createEl("h2", { text: "\u6570\u636E\u6E90\u914D\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("Daily Note \u8DEF\u5F84").setDesc("Daily Note \u6587\u4EF6\u5939\u8DEF\u5F84\uFF08\u8F93\u5165\u65F6\u81EA\u52A8\u641C\u7D22\uFF09").addText((text) => {
      text.setPlaceholder("\u8F93\u5165\u641C\u7D22\u6587\u4EF6\u5939...").setValue(this.plugin.settings.dailyNotePath).onChange(async (value) => {
        this.plugin.settings.dailyNotePath = value;
        await this.plugin.saveSettings();
      });
      new FolderSuggest(this.app, text.inputEl);
    });
    new import_obsidian.Setting(containerEl).setName("Daily Note \u6A21\u677F").setDesc("\u521B\u5EFA\u65B0\u65E5\u8BB0\u65F6\u4F7F\u7528\u7684\u6A21\u677F\u6587\u4EF6\uFF08\u7559\u7A7A\u4F7F\u7528\u9ED8\u8BA4\u6A21\u677F\uFF09").addText((text) => {
      text.setPlaceholder("\u5982 Templates/Daily Note.md").setValue(this.plugin.settings.dailyNoteTemplatePath).onChange(async (value) => {
        this.plugin.settings.dailyNoteTemplatePath = value;
        await this.plugin.saveSettings();
      });
      new FileSuggest(this.app, text.inputEl, "md");
    });
    new import_obsidian.Setting(containerEl).setName("\u5305\u542B Daily Note \u4EFB\u52A1").addToggle((toggle) => toggle.setValue(this.plugin.settings.taskSources.daily).onChange(async (value) => {
      this.plugin.settings.taskSources.daily = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Nike \u65E5\u5386\u8DEF\u5F84").setDesc("Nike \u9879\u76EE\u65E5\u5386\u6587\u4EF6\u5939\u8DEF\u5F84\uFF08\u8F93\u5165\u65F6\u81EA\u52A8\u641C\u7D22\uFF09").addText((text) => {
      text.setPlaceholder("\u8F93\u5165\u641C\u7D22\u6587\u4EF6\u5939...").setValue(this.plugin.settings.nikePath).onChange(async (value) => {
        this.plugin.settings.nikePath = value;
        await this.plugin.saveSettings();
      });
      new FolderSuggest(this.app, text.inputEl);
    });
    new import_obsidian.Setting(containerEl).setName("\u5305\u542B Nike \u9879\u76EE\u4EFB\u52A1").addToggle((toggle) => toggle.setValue(this.plugin.settings.taskSources.nike).onChange(async (value) => {
      this.plugin.settings.taskSources.nike = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u5468\u671F\u4EFB\u52A1\u914D\u7F6E\u6587\u4EF6").setDesc("\u5468\u671F\u4EFB\u52A1\u914D\u7F6E\u8868\u683C\u6240\u5728\u7684 .md \u6587\u4EF6\uFF08\u8F93\u5165\u65F6\u81EA\u52A8\u641C\u7D22\uFF09").addText((text) => {
      text.setPlaceholder("\u8F93\u5165\u641C\u7D22\u6587\u4EF6...").setValue(this.plugin.settings.recurringConfigPath).onChange(async (value) => {
        this.plugin.settings.recurringConfigPath = value;
        await this.plugin.saveSettings();
      });
      new FileSuggest(this.app, text.inputEl, "md");
    });
    new import_obsidian.Setting(containerEl).setName("\u5305\u542B\u5468\u671F\u4EFB\u52A1").addToggle((toggle) => toggle.setValue(this.plugin.settings.taskSources.recurring).onChange(async (value) => {
      this.plugin.settings.taskSources.recurring = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u5305\u542B\u8282\u5047\u65E5").setDesc("\u5305\u542B\u5E26\u6709 #holiday \u6807\u7B7E\u6216 type: holiday \u7684\u4EFB\u52A1").addToggle((toggle) => toggle.setValue(this.plugin.settings.taskSources.holiday).onChange(async (value) => {
      this.plugin.settings.taskSources.holiday = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h2", { text: "\u4EFB\u52A1\u79FB\u52A8\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u79FB\u52A8\u524D\u786E\u8BA4").setDesc("\u79FB\u52A8\u4EFB\u52A1\u5230\u5176\u4ED6\u65E5\u671F\u524D\u663E\u793A\u786E\u8BA4\u5BF9\u8BDD\u6846").addToggle((toggle) => toggle.setValue(this.plugin.settings.confirmBeforeMove).onChange(async (value) => {
      this.plugin.settings.confirmBeforeMove = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u5141\u8BB8\u79FB\u52A8\u5230\u8FC7\u53BB").setDesc("\u5141\u8BB8\u5C06\u4EFB\u52A1\u79FB\u52A8\u5230\u8FC7\u53BB\u7684\u65E5\u671F").addToggle((toggle) => toggle.setValue(this.plugin.settings.allowMoveToPast).onChange(async (value) => {
      this.plugin.settings.allowMoveToPast = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/services/DailyTaskSource.ts
var import_obsidian2 = require("obsidian");

// src/types.ts
var SOURCE_LABELS = {
  daily: "\u{1F4C5} Daily",
  nike: "\u{1F45F} Nike",
  holiday: "\u{1F389} Holiday",
  recurring: "\u{1F504} \u5468\u671F"
};

// src/services/DailyTaskSource.ts
var DailyTaskSource = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  /**
   * 获取 Daily Note 中的未完成任务
   */
  async getTasks(dv) {
    var _a, _b;
    const dailyPath = this.settings.dailyNotePath;
    if (!dailyPath) {
      return [];
    }
    const folder = this.app.vault.getAbstractFileByPath(dailyPath);
    if (!folder) {
      console.warn(`[TaskReminder] Daily Note path not found: ${dailyPath}`);
      return [];
    }
    const tasks = [];
    const todayStr = (0, import_obsidian2.moment)().format("YYYY-MM-DD");
    const today = (0, import_obsidian2.moment)().startOf("day");
    try {
      const pages = dv.pages(`"${dailyPath}"`);
      const allTasks = pages.file.tasks.where((t) => !t.completed && !t.checked).array();
      for (const task of allTasks) {
        const filePath = task.path || ((_a = task.link) == null ? void 0 : _a.path) || "";
        const fileName = ((_b = filePath.split("/").pop()) == null ? void 0 : _b.replace(".md", "")) || "";
        const fileDate = (0, import_obsidian2.moment)(fileName, "YYYY-MM-DD", true);
        if (fileDate.isValid() && fileDate.isSameOrBefore(today, "day")) {
          const fullText = task.text || "";
          if (fullText.includes("\u{1F504}")) {
            continue;
          }
          const isMeeting = this.isMeetingTask(task.tags || []);
          const text = this.truncateText(fullText, 60);
          tasks.push({
            id: `${filePath}:${task.line}`,
            source: "daily",
            sourceLabel: SOURCE_LABELS.daily,
            text,
            fullText,
            isMeeting,
            filePath,
            line: task.line,
            dueDate: fileName
          });
        }
      }
    } catch (e) {
      console.error("[TaskReminder] Error querying daily tasks:", e);
      throw e;
    }
    return tasks;
  }
  /**
   * 检查是否为会议任务
   * 匹配: #meeting, #Meeting, #team-meeting 等
   */
  isMeetingTask(tags) {
    return tags.some(
      (tag) => tag.toLowerCase().includes("meeting")
    );
  }
  /**
   * 截断文本
   */
  truncateText(text, maxLength) {
    let cleaned = text.replace(/^[\s-]*\[.\]\s*/, "").replace(/#\S+/g, "").trim();
    if (cleaned.length <= maxLength) {
      return cleaned;
    }
    return cleaned.substring(0, maxLength - 3) + "...";
  }
};

// src/services/NikeTaskSource.ts
var import_obsidian3 = require("obsidian");
var NikeTaskSource = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  /**
   * 获取 Nike 项目中的待办事件
   */
  async getTasks(dv) {
    var _a, _b;
    const nikePath = this.settings.nikePath;
    if (!nikePath) {
      return [];
    }
    const folder = this.app.vault.getAbstractFileByPath(nikePath);
    if (!folder) {
      console.warn(`[TaskReminder] Nike path not found: ${nikePath}`);
      return [];
    }
    const tasks = [];
    const today = (0, import_obsidian3.moment)().startOf("day");
    try {
      const pages = dv.pages(`"${nikePath}"`).where((p) => {
        var _a2;
        const pathParts = (((_a2 = p.file) == null ? void 0 : _a2.folder) || "").split("/");
        return pathParts.some((part) => part.toLowerCase() === "events");
      }).where((p) => {
        var _a2;
        const frontmatter = ((_a2 = p.file) == null ? void 0 : _a2.frontmatter) || p;
        return "Done" in frontmatter && frontmatter.Done !== true;
      }).array();
      for (const page of pages) {
        const dueDate = page["Due Date"];
        const parsedDate = this.parseDate(dueDate);
        if (parsedDate && parsedDate.isSameOrBefore(today, "day")) {
          const filePath = ((_a = page.file) == null ? void 0 : _a.path) || "";
          const fileName = ((_b = page.file) == null ? void 0 : _b.name) || "";
          const dueDateStr = parsedDate.format("YYYY-MM-DD");
          tasks.push({
            id: `${filePath}:0`,
            source: "nike",
            sourceLabel: SOURCE_LABELS.nike,
            text: fileName,
            fullText: fileName,
            isMeeting: false,
            filePath,
            line: 0,
            dueDate: dueDateStr
          });
        }
      }
    } catch (e) {
      console.error("[TaskReminder] Error querying Nike tasks:", e);
      throw e;
    }
    return tasks;
  }
  /**
   * 解析日期值
   */
  parseDate(dateValue) {
    if (!dateValue) return null;
    if (dateValue.ts) {
      return (0, import_obsidian3.moment)(dateValue.ts);
    }
    if (typeof dateValue === "string") {
      const parsed2 = (0, import_obsidian3.moment)(dateValue, ["YYYY-MM-DD", "YYYY/MM/DD"], true);
      return parsed2.isValid() ? parsed2 : null;
    }
    const parsed = (0, import_obsidian3.moment)(dateValue);
    return parsed.isValid() ? parsed : null;
  }
};

// src/services/HolidayTaskSource.ts
var import_obsidian4 = require("obsidian");
var HolidayTaskSource = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  /**
   * 获取今日节假日任务
   */
  async getTasks(dv) {
    var _a, _b;
    const tasks = [];
    const todayStr = (0, import_obsidian4.moment)().format("YYYY-MM-DD");
    const today = (0, import_obsidian4.moment)().startOf("day");
    try {
      const pages = dv.pages().where((p) => {
        var _a2;
        const tags = ((_a2 = p.file) == null ? void 0 : _a2.tags) || [];
        if (tags.includes("#holiday")) return true;
        if (p.type === "holiday") return true;
        if (Array.isArray(p.type) && p.type.includes("holiday")) return true;
        return false;
      }).array();
      for (const page of pages) {
        const pageDate = this.resolveDateFromPage(page);
        if (pageDate && pageDate.isSame(today, "day")) {
          const filePath = ((_a = page.file) == null ? void 0 : _a.path) || "";
          const fileName = page.name || ((_b = page.file) == null ? void 0 : _b.name) || "";
          tasks.push({
            id: `${filePath}:0`,
            source: "holiday",
            sourceLabel: SOURCE_LABELS.holiday,
            text: fileName,
            fullText: fileName,
            isMeeting: false,
            filePath,
            line: 0,
            dueDate: todayStr
          });
        }
      }
    } catch (e) {
      console.error("[TaskReminder] Error querying holiday tasks:", e);
      throw e;
    }
    return tasks;
  }
  /**
   * 从页面解析日期
   * 优先级：p.date > p.file.day > p.file.name
   */
  resolveDateFromPage(page) {
    var _a, _b;
    if (page.date) {
      const parsed = this.parseDate(page.date);
      if (parsed) return parsed;
    }
    if ((_a = page.file) == null ? void 0 : _a.day) {
      const parsed = this.parseDate(page.file.day);
      if (parsed) return parsed;
    }
    if ((_b = page.file) == null ? void 0 : _b.name) {
      const parsed = (0, import_obsidian4.moment)(page.file.name, ["YYYY-MM-DD", "YYYY/MM/DD"], true);
      if (parsed.isValid()) return parsed;
    }
    return null;
  }
  /**
   * 解析日期值
   */
  parseDate(dateValue) {
    if (!dateValue) return null;
    if (dateValue.ts) {
      return (0, import_obsidian4.moment)(dateValue.ts);
    }
    if (typeof dateValue === "string") {
      const parsed2 = (0, import_obsidian4.moment)(dateValue, ["YYYY-MM-DD", "YYYY/MM/DD"], true);
      return parsed2.isValid() ? parsed2 : null;
    }
    const parsed = (0, import_obsidian4.moment)(dateValue);
    return parsed.isValid() ? parsed : null;
  }
};

// src/services/RecurringTaskSource.ts
var import_obsidian5 = require("obsidian");
var RecurringTaskSource = class {
  constructor(app, settings) {
    /** 月份名称映射 */
    this.monthNames = [
      "",
      "01.January",
      "02.February",
      "03.March",
      "04.April",
      "05.May",
      "06.June",
      "07.July",
      "08.August",
      "09.September",
      "10.October",
      "11.November",
      "12.December"
    ];
    this.app = app;
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  /**
   * 获取今日周期任务（仅返回已存在于 Daily Note 且未完成的任务）
   * 修复 P0-1：避免与 pendingTasks 重复展示
   */
  async getTasks(dv) {
    const result = await this.getFullResult(dv);
    return result.tasks;
  }
  /**
   * 解析周期任务配置文件
   */
  async parseConfigFile(configPath) {
    const file = this.app.vault.getAbstractFileByPath(configPath);
    if (!file) {
      console.warn(`[TaskReminder] Recurring config file not found: ${configPath}`);
      return [];
    }
    const content = await this.app.vault.read(file);
    const configs = [];
    const tableRegex = /\|\s*([^|]+)\s*\|\s*(daily|weekly|monthly)\s*\|\s*([^|]+)\s*\|\s*(replace|accumulate|skip)\s*\|/gi;
    let match;
    while ((match = tableRegex.exec(content)) !== null) {
      const name = match[1].trim();
      const type = match[2].trim().toLowerCase();
      const trigger = match[3].trim();
      const mode = match[4].trim().toLowerCase();
      if (name === "\u4EFB\u52A1\u540D\u79F0" || name.includes("---")) {
        continue;
      }
      configs.push({ name, type, trigger, mode });
    }
    return configs;
  }
  /**
   * 筛选今日应显示的任务
   */
  filterTodayTasks(configs) {
    const todayWeekday = (0, import_obsidian5.moment)().isoWeekday();
    const todayDay = (0, import_obsidian5.moment)().date();
    const todayMonth = (0, import_obsidian5.moment)().month() + 1;
    return configs.filter((config) => {
      if (config.type === "daily") {
        return true;
      }
      if (config.type === "weekly") {
        return parseInt(config.trigger) === todayWeekday;
      }
      if (config.type === "monthly") {
        const monthlyMatch = config.trigger.match(/^(\d+)(?:\s*\(([^)]+)\))?$/);
        if (monthlyMatch) {
          const day = parseInt(monthlyMatch[1]);
          if (day !== todayDay) {
            return false;
          }
          if (monthlyMatch[2]) {
            const months = monthlyMatch[2].split(",").map((m) => parseInt(m.trim()));
            return months.includes(todayMonth);
          }
          return true;
        }
      }
      return false;
    });
  }
  /**
   * 检查日记中周期任务的完成状态
   */
  async checkDailyNoteStatus(configs) {
    const statusMap = /* @__PURE__ */ new Map();
    const dailyPath = this.getDailyNotePath();
    const file = this.app.vault.getAbstractFileByPath(dailyPath);
    if (!file) {
      for (const config of configs) {
        statusMap.set(config.name, { existsInDaily: false, isCompleted: false });
      }
      return statusMap;
    }
    const content = await this.app.vault.read(file);
    for (const config of configs) {
      const name = config.name;
      const pendingRegex = new RegExp(`- \\[ \\] \u{1F504}\\s+${this.escapeRegex(name)}`, "i");
      const completedRegex = new RegExp(`- \\[x\\] \u{1F504}\\s+${this.escapeRegex(name)}`, "i");
      const isPending = pendingRegex.test(content);
      const isCompleted = completedRegex.test(content);
      statusMap.set(name, {
        existsInDaily: isPending || isCompleted,
        isCompleted
      });
    }
    return statusMap;
  }
  /**
   * 转义正则表达式特殊字符
   */
  escapeRegex(str) {
    return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
  /**
   * 获取完整的周期任务结果（包含待生成任务）
   * 用于 F4 功能
   */
  async getFullResult(dv) {
    const configPath = this.settings.recurringConfigPath;
    if (!configPath) {
      return { tasks: [], pendingTasks: [] };
    }
    const tasks = [];
    const pendingTasks = [];
    const todayStr = (0, import_obsidian5.moment)().format("YYYY-MM-DD");
    try {
      const configs = await this.parseConfigFile(configPath);
      if (configs.length === 0) {
        return { tasks: [], pendingTasks: [] };
      }
      const todayConfigs = this.filterTodayTasks(configs);
      const dailyStatus = await this.checkDailyNoteStatus(todayConfigs);
      for (const config of todayConfigs) {
        const status = dailyStatus.get(config.name);
        if (status == null ? void 0 : status.isCompleted) {
          continue;
        }
        if (status == null ? void 0 : status.existsInDaily) {
          tasks.push({
            id: `recurring:${config.name}`,
            source: "recurring",
            sourceLabel: SOURCE_LABELS.recurring,
            text: config.name,
            fullText: `\u{1F504} ${config.name}`,
            isMeeting: false,
            filePath: this.getDailyNotePath(),
            line: void 0,
            dueDate: todayStr
          });
        } else {
          pendingTasks.push({
            name: config.name,
            type: config.type,
            trigger: config.trigger
          });
        }
      }
    } catch (e) {
      console.error("[TaskReminder] Error querying recurring tasks:", e);
      throw e;
    }
    return { tasks, pendingTasks };
  }
  /**
   * 获取今日日记路径（公开方法，供写入服务使用）
   */
  getDailyNotePath() {
    const dailyPath = this.settings.dailyNotePath;
    const year = (0, import_obsidian5.moment)().format("YYYY");
    const month = (0, import_obsidian5.moment)().month() + 1;
    const dateStr = (0, import_obsidian5.moment)().format("YYYY-MM-DD");
    return `${dailyPath}/${year}/${this.monthNames[month]}/${dateStr}.md`;
  }
};

// src/services/TaskDataService.ts
var CACHE_TTL = 6e4;
var TaskDataService = class {
  constructor(app, settings) {
    this.cache = null;
    this.cacheTime = 0;
    this.app = app;
    this.settings = settings;
    this.dailySource = new DailyTaskSource(app, settings);
    this.nikeSource = new NikeTaskSource(app, settings);
    this.holidaySource = new HolidayTaskSource(app, settings);
    this.recurringSource = new RecurringTaskSource(app, settings);
  }
  /** 获取 Dataview API */
  getDataviewApi() {
    var _a, _b, _c;
    return ((_c = (_b = (_a = this.app.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b.dataview) == null ? void 0 : _c.api) || null;
  }
  /** 检查缓存是否有效 */
  isCacheValid() {
    return this.cache !== null && Date.now() - this.cacheTime < CACHE_TTL;
  }
  /** 清除缓存 */
  invalidateCache() {
    this.cache = null;
    this.cacheTime = 0;
  }
  /** 更新设置引用 */
  updateSettings(settings) {
    this.settings = settings;
    this.dailySource.updateSettings(settings);
    this.nikeSource.updateSettings(settings);
    this.holidaySource.updateSettings(settings);
    this.recurringSource.updateSettings(settings);
    this.invalidateCache();
  }
  /**
   * 获取今日所有任务
   */
  async getTodayTasks() {
    const result = await this.getTaskData();
    return result.tasks;
  }
  /**
   * 获取今日任务数量
   */
  async getTaskCount() {
    const result = await this.getTaskData();
    return result.tasks.length;
  }
  /**
   * 获取完整数据结果（含分类统计）
   */
  async getTaskData() {
    if (this.isCacheValid() && this.cache) {
      return this.cache;
    }
    const dv = this.getDataviewApi();
    if (!dv) {
      return {
        tasks: [],
        dailyCount: 0,
        nikeCount: 0,
        holidayCount: 0,
        recurringCount: 0,
        errors: [{
          source: "dataview",
          message: "\u9700\u8981\u5B89\u88C5\u5E76\u542F\u7528 Dataview \u63D2\u4EF6",
          recoverable: false
        }]
      };
    }
    const allTasks = [];
    const errors = [];
    if (this.settings.taskSources.daily) {
      try {
        const dailyTasks = await this.dailySource.getTasks(dv);
        allTasks.push(...dailyTasks);
      } catch (e) {
        console.warn("[TaskReminder] Daily tasks query failed:", e);
        errors.push({
          source: "daily",
          message: e instanceof Error ? e.message : String(e),
          recoverable: true
        });
      }
    }
    if (this.settings.taskSources.nike) {
      try {
        const nikeTasks = await this.nikeSource.getTasks(dv);
        allTasks.push(...nikeTasks);
      } catch (e) {
        console.warn("[TaskReminder] Nike tasks query failed:", e);
        errors.push({
          source: "nike",
          message: e instanceof Error ? e.message : String(e),
          recoverable: true
        });
      }
    }
    if (this.settings.taskSources.holiday) {
      try {
        const holidayTasks = await this.holidaySource.getTasks(dv);
        allTasks.push(...holidayTasks);
      } catch (e) {
        console.warn("[TaskReminder] Holiday tasks query failed:", e);
        errors.push({
          source: "holiday",
          message: e instanceof Error ? e.message : String(e),
          recoverable: true
        });
      }
    }
    if (this.settings.taskSources.recurring) {
      try {
        const recurringTasks = await this.recurringSource.getTasks(dv);
        allTasks.push(...recurringTasks);
      } catch (e) {
        console.warn("[TaskReminder] Recurring tasks query failed:", e);
        errors.push({
          source: "recurring",
          message: e instanceof Error ? e.message : String(e),
          recoverable: true
        });
      }
    }
    const result = {
      tasks: allTasks,
      dailyCount: allTasks.filter((t) => t.source === "daily").length,
      nikeCount: allTasks.filter((t) => t.source === "nike").length,
      holidayCount: allTasks.filter((t) => t.source === "holiday").length,
      recurringCount: allTasks.filter((t) => t.source === "recurring").length,
      errors
    };
    this.cache = result;
    this.cacheTime = Date.now();
    return result;
  }
  /**
   * 获取待生成的周期任务（F4 功能）
   * 修复 P0-2：若 dailyNotePath 未配置，返回空数组
   */
  async getPendingRecurringTasks() {
    var _a;
    if (!this.settings.taskSources.recurring) {
      return [];
    }
    if (!((_a = this.settings.dailyNotePath) == null ? void 0 : _a.trim())) {
      return [];
    }
    const dv = this.getDataviewApi();
    if (!dv) {
      return [];
    }
    try {
      const result = await this.recurringSource.getFullResult(dv);
      return result.pendingTasks;
    } catch (e) {
      console.warn("[TaskReminder] Failed to get pending recurring tasks:", e);
      return [];
    }
  }
};

// src/services/DailyNoteService.ts
var import_obsidian6 = require("obsidian");
var DailyNoteService = class {
  constructor(app, settings) {
    /** 月份名称映射 */
    this.monthNames = [
      "",
      "01.January",
      "02.February",
      "03.March",
      "04.April",
      "05.May",
      "06.June",
      "07.July",
      "08.August",
      "09.September",
      "10.October",
      "11.November",
      "12.December"
    ];
    this.app = app;
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  /**
   * 获取今日日记路径
   * 修复 P0-2：路径规范化处理
   */
  getDailyNotePath() {
    return this.getDailyNotePathForDate((0, import_obsidian6.moment)());
  }
  /**
   * 获取指定日期的 Daily Note 路径（F5/F6 使用）
   * @param date 目标日期
   */
  getDailyNotePathForDate(date) {
    var _a;
    let dailyPath = ((_a = this.settings.dailyNotePath) == null ? void 0 : _a.trim()) || "";
    dailyPath = dailyPath.replace(/\/+$/, "");
    const year = date.format("YYYY");
    const month = date.month() + 1;
    const dateStr = date.format("YYYY-MM-DD");
    return `${dailyPath}/${year}/${this.monthNames[month]}/${dateStr}.md`;
  }
  /**
   * 检查 dailyNotePath 是否已配置
   */
  isDailyNotePathConfigured() {
    var _a;
    return !!((_a = this.settings.dailyNotePath) == null ? void 0 : _a.trim());
  }
  /**
   * F5: 写入单个任务到指定日期的 Daily Note
   * @param content 任务内容（不含 `- [ ]` 前缀）
   * @param date 目标日期
   */
  async writeTask(content, date) {
    if (!this.isDailyNotePathConfigured()) {
      throw new Error("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E Daily Note \u8DEF\u5F84");
    }
    const taskLine = `- [ ] ${content}`;
    await this.writeTaskLine(taskLine, date);
  }
  /**
   * F6: 写入完整任务行到指定日期（用于移动任务）
   * @param taskLine 完整任务行（如 `- [ ] 任务内容`）
   * @param date 目标日期
   */
  async writeTaskLine(taskLine, date) {
    if (!this.isDailyNotePathConfigured()) {
      throw new Error("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E Daily Note \u8DEF\u5F84");
    }
    const dailyPath = this.getDailyNotePathForDate(date);
    let file = this.app.vault.getAbstractFileByPath(dailyPath);
    if (!file) {
      file = await this.createDailyNoteForDate(dailyPath, date);
    }
    if (!(file instanceof import_obsidian6.TFile)) {
      throw new Error(`\u65E0\u6CD5\u8BBF\u95EE\u65E5\u8BB0\u6587\u4EF6: ${dailyPath}`);
    }
    let fileContent = await this.app.vault.read(file);
    if (fileContent.length > 0 && !fileContent.endsWith("\n")) {
      fileContent += "\n";
    }
    fileContent += taskLine + "\n";
    await this.app.vault.modify(file, fileContent);
  }
  /**
   * 创建指定日期的 Daily Note（F5/F6 使用）
   * P0-1: 统一调用 createDailyNoteWithTemplate
   */
  async createDailyNoteForDate(path, date) {
    return await this.createDailyNoteWithTemplate(path, date);
  }
  /**
   * 将周期任务写入 Daily Note
   * @param tasks 待生成的周期任务列表
   * @returns 成功写入的任务数量
   * 修复 P0-2：写入前校验 dailyNotePath
   * 修复 P1-3：添加去重和二次确认
   */
  async writeRecurringTasks(tasks) {
    if (tasks.length === 0) {
      return 0;
    }
    if (!this.isDailyNotePathConfigured()) {
      throw new Error("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E Daily Note \u8DEF\u5F84");
    }
    const dailyPath = this.getDailyNotePath();
    let file = this.app.vault.getAbstractFileByPath(dailyPath);
    if (!file) {
      file = await this.createDailyNote(dailyPath);
    }
    if (!(file instanceof import_obsidian6.TFile)) {
      throw new Error(`\u65E0\u6CD5\u8BBF\u95EE\u65E5\u8BB0\u6587\u4EF6: ${dailyPath}`);
    }
    let content = await this.app.vault.read(file);
    const uniqueTasks = this.deduplicateTasks(tasks);
    const tasksToWrite = uniqueTasks.filter((task) => {
      const taskPattern = new RegExp(`- \\[.\\] \u{1F504}\\s+${this.escapeRegex(task.name)}`, "i");
      return !taskPattern.test(content);
    });
    if (tasksToWrite.length === 0) {
      return 0;
    }
    const taskLines = tasksToWrite.map((task) => `- [ ] \u{1F504} ${task.name}`).join("\n");
    if (content.length > 0 && !content.endsWith("\n")) {
      content += "\n";
    }
    content += "\n" + taskLines + "\n";
    await this.app.vault.modify(file, content);
    return tasksToWrite.length;
  }
  /**
   * 对任务按名称去重
   */
  deduplicateTasks(tasks) {
    const seen = /* @__PURE__ */ new Set();
    return tasks.filter((task) => {
      if (seen.has(task.name)) {
        return false;
      }
      seen.add(task.name);
      return true;
    });
  }
  /**
   * 转义正则表达式特殊字符
   */
  escapeRegex(str) {
    return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
  /**
   * 创建 Daily Note 文件（F4 使用）
   * P0-1: 统一调用 createDailyNoteWithTemplate
   */
  async createDailyNote(path) {
    return await this.createDailyNoteWithTemplate(path, (0, import_obsidian6.moment)());
  }
  /**
   * F7: 使用模板创建 Daily Note
   * 统一创建入口，F4/F5/F6 均调用此方法
   */
  async createDailyNoteWithTemplate(path, date) {
    var _a;
    const folderPath = path.substring(0, path.lastIndexOf("/"));
    await this.ensureFolderExists(folderPath);
    let content;
    const templatePath = (_a = this.settings.dailyNoteTemplatePath) == null ? void 0 : _a.trim();
    if (templatePath) {
      const templateFile = this.app.vault.getAbstractFileByPath(templatePath);
      if (templateFile instanceof import_obsidian6.TFile) {
        try {
          const templateContent = await this.app.vault.read(templateFile);
          content = this.processTemplate(templateContent, date);
        } catch (error) {
          console.error(`[TaskReminder] \u6A21\u677F\u8BFB\u53D6\u5931\u8D25: ${error}`);
          new import_obsidian6.Notice(`\u6A21\u677F\u8BFB\u53D6\u5931\u8D25\uFF0C\u4F7F\u7528\u9ED8\u8BA4\u6A21\u677F: ${error}`, 5e3);
          content = this.getDefaultTemplate(date);
        }
      } else {
        console.warn(`[TaskReminder] \u6A21\u677F\u6587\u4EF6\u4E0D\u5B58\u5728: ${templatePath}`);
        new import_obsidian6.Notice(`\u6A21\u677F\u6587\u4EF6\u4E0D\u5B58\u5728\uFF0C\u4F7F\u7528\u9ED8\u8BA4\u6A21\u677F: ${templatePath}`, 5e3);
        content = this.getDefaultTemplate(date);
      }
    } else {
      content = this.getDefaultTemplate(date);
    }
    return await this.app.vault.create(path, content);
  }
  /**
   * F7: 处理模板变量
   */
  processTemplate(template, date) {
    const dayEnMap = {
      0: "Sunday",
      1: "Monday",
      2: "Tuesday",
      3: "Wednesday",
      4: "Thursday",
      5: "Friday",
      6: "Saturday"
    };
    const dayZhMap = {
      0: "\u661F\u671F\u65E5",
      1: "\u661F\u671F\u4E00",
      2: "\u661F\u671F\u4E8C",
      3: "\u661F\u671F\u4E09",
      4: "\u661F\u671F\u56DB",
      5: "\u661F\u671F\u4E94",
      6: "\u661F\u671F\u516D"
    };
    return template.replace(/\{\{date:([^}]+)\}\}/g, (_, format) => date.format(format)).replace(/\{\{date\}\}/g, date.format("YYYY-MM-DD")).replace(/\{\{day\}\}/g, dayEnMap[date.day()]).replace(/\{\{day:zh\}\}/g, dayZhMap[date.day()]).replace(/\{\{time\}\}/g, (0, import_obsidian6.moment)().format("HH:mm")).replace(/\{\{title\}\}/g, date.format("YYYY-MM-DD"));
  }
  /**
   * F7: 默认模板（向后兼容）
   */
  getDefaultTemplate(date) {
    const dateStr = date.format("YYYY-MM-DD");
    const dayOfWeek = date.format("dddd");
    return `---
date: ${dateStr}
day: ${dayOfWeek}
---

# ${dateStr}

`;
  }
  /**
   * 确保文件夹存在
   */
  async ensureFolderExists(folderPath) {
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (folder instanceof import_obsidian6.TFolder) {
      return;
    }
    const parts = folderPath.split("/");
    let currentPath = "";
    for (const part of parts) {
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      const existing = this.app.vault.getAbstractFileByPath(currentPath);
      if (!existing) {
        await this.app.vault.createFolder(currentPath);
      }
    }
  }
};

// src/services/TaskMoveService.ts
var import_obsidian7 = require("obsidian");
var TaskMoveService = class {
  constructor(app, dailyNoteService, settings) {
    this.app = app;
    this.dailyNoteService = dailyNoteService;
    this.settings = settings;
  }
  /**
   * 更新设置引用
   */
  updateSettings(settings) {
    this.settings = settings;
  }
  /**
   * 移动任务到目标日期
   * 实现 Write-Then-Delete 一致性保证
   * @param task 要移动的任务
   * @param targetDate 目标日期
   */
  async moveTask(task, targetDate) {
    const fromPath = task.filePath;
    const toPath = this.dailyNoteService.getDailyNotePathForDate(targetDate);
    if (task.source !== "daily") {
      throw new Error("\u4EC5\u652F\u6301\u79FB\u52A8 Daily Note \u4E2D\u7684\u4EFB\u52A1");
    }
    if (task.line === void 0) {
      throw new Error("\u4EFB\u52A1\u884C\u53F7\u4FE1\u606F\u7F3A\u5931");
    }
    if (!this.settings.allowMoveToPast && targetDate.isBefore((0, import_obsidian7.moment)(), "day")) {
      throw new Error("\u4E0D\u5141\u8BB8\u79FB\u52A8\u5230\u8FC7\u53BB\u65E5\u671F");
    }
    if (fromPath === toPath) {
      throw new Error("\u4EFB\u52A1\u5DF2\u5728\u76EE\u6807\u65E5\u671F");
    }
    const fromFile = this.app.vault.getAbstractFileByPath(fromPath);
    if (!(fromFile instanceof import_obsidian7.TFile)) {
      throw new Error(`\u539F\u6587\u4EF6\u4E0D\u5B58\u5728: ${fromPath}`);
    }
    const fromContent = await this.app.vault.read(fromFile);
    const lines = fromContent.split("\n");
    if (task.line >= lines.length) {
      throw new Error("\u4EFB\u52A1\u884C\u53F7\u8D85\u51FA\u6587\u4EF6\u8303\u56F4");
    }
    const taskLine = lines[task.line];
    await this.dailyNoteService.writeTaskLine(taskLine, targetDate);
    try {
      lines.splice(task.line, 1);
      await this.app.vault.modify(fromFile, lines.join("\n"));
    } catch (deleteError) {
      console.warn("[TaskMoveService] \u5220\u9664\u6E90\u4EFB\u52A1\u884C\u5931\u8D25\uFF0C\u4EFB\u52A1\u53EF\u80FD\u91CD\u590D:", deleteError);
      return {
        success: true,
        fromPath,
        toPath,
        taskText: task.fullText,
        error: "\u4EFB\u52A1\u5DF2\u590D\u5236\u5230\u76EE\u6807\u65E5\u671F\uFF0C\u4F46\u6E90\u6587\u4EF6\u5220\u9664\u5931\u8D25\uFF0C\u8BF7\u624B\u52A8\u6E05\u7406"
      };
    }
    return {
      success: true,
      fromPath,
      toPath,
      taskText: task.fullText
    };
  }
  /**
   * 检查任务是否可移动
   */
  canMoveTask(task) {
    if (task.source !== "daily") {
      return { canMove: false, reason: "\u4EC5\u652F\u6301\u79FB\u52A8 Daily Note \u4E2D\u7684\u4EFB\u52A1" };
    }
    if (task.line === void 0) {
      return { canMove: false, reason: "\u4EFB\u52A1\u884C\u53F7\u4FE1\u606F\u7F3A\u5931" };
    }
    return { canMove: true };
  }
};

// src/ui/ReminderModal.ts
var import_obsidian8 = require("obsidian");
var ReminderModal = class extends import_obsidian8.Modal {
  constructor(app, tasks, pendingRecurringTasks = [], onGenerate, onMoveTask) {
    super(app);
    this.tasks = tasks;
    this.pendingRecurringTasks = pendingRecurringTasks;
    this.onGenerate = onGenerate;
    this.onMoveTask = onMoveTask;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText(`\u{1F4CB} \u4ECA\u65E5\u5F85\u529E\u63D0\u9192 (${this.tasks.length})`);
    const container = contentEl.createDiv({ cls: "task-reminder-list" });
    const groupedTasks = this.groupTasksBySource();
    for (const [source, tasks] of Object.entries(groupedTasks)) {
      if (tasks.length === 0) continue;
      const groupEl = container.createDiv({ cls: "task-reminder-group" });
      const groupTitle = groupEl.createDiv({ cls: "task-reminder-group-title" });
      groupTitle.setText(`${tasks[0].sourceLabel} (${tasks.length})`);
      for (const task of tasks) {
        const itemEl = groupEl.createDiv({ cls: "task-reminder-item" });
        const iconEl = itemEl.createSpan({ cls: "task-icon" });
        iconEl.setText(task.isMeeting ? "\u{1F5D3}\uFE0F" : "\u2022");
        const textEl = itemEl.createSpan({ cls: "task-text" });
        textEl.setText(task.text);
        if (task.isMeeting) {
          textEl.addClass("task-meeting");
        }
        if (task.dueDate && this.isOverdue(task.dueDate)) {
          const overdueEl = itemEl.createSpan({ cls: "task-overdue" });
          overdueEl.setText("\u26A0\uFE0F \u8FC7\u671F");
        }
        if (task.source === "daily" && this.onMoveTask) {
          const moveBtn = itemEl.createEl("button", {
            cls: "task-reminder-move-btn",
            attr: { "aria-label": "\u79FB\u52A8\u5230\u5176\u4ED6\u65E5\u671F" }
          });
          moveBtn.setText("\u{1F4C5}");
          moveBtn.addEventListener("click", (e) => {
            e.stopPropagation();
            this.onMoveTask(task);
          });
        }
        itemEl.addEventListener("click", () => this.navigateToTask(task));
        itemEl.style.cursor = "pointer";
        itemEl.setAttribute("title", task.fullText);
        if (import_obsidian8.Platform.isDesktop && task.source === "daily" && this.onMoveTask) {
          itemEl.addEventListener("contextmenu", (e) => {
            e.preventDefault();
            this.showMoveMenu(task, e);
          });
        }
        if (import_obsidian8.Platform.isMobile && task.source === "daily" && this.onMoveTask) {
          this.setupLongPressGesture(itemEl, task);
        }
      }
    }
    this.renderPendingSection(container);
    const btnContainer = contentEl.createDiv({ cls: "modal-button-container" });
    if (this.pendingRecurringTasks.length > 0 && this.onGenerate) {
      const generateBtn = btnContainer.createEl("button", {
        text: `\u{1F504} \u751F\u6210\u5230 Daily Note (${this.pendingRecurringTasks.length})`
      });
      generateBtn.addEventListener("click", async () => {
        generateBtn.disabled = true;
        generateBtn.setText("\u751F\u6210\u4E2D...");
        try {
          const count = await this.onGenerate(this.pendingRecurringTasks);
          new import_obsidian8.Notice(`\u2705 \u5DF2\u751F\u6210 ${count} \u4E2A\u5468\u671F\u4EFB\u52A1\u5230 Daily Note`);
          this.close();
        } catch (e) {
          new import_obsidian8.Notice(`\u274C \u751F\u6210\u5931\u8D25: ${e.message}`);
          generateBtn.disabled = false;
          generateBtn.setText(`\u{1F504} \u751F\u6210\u5230 Daily Note (${this.pendingRecurringTasks.length})`);
        }
      });
    }
    const closeBtn = btnContainer.createEl("button", { text: "\u77E5\u9053\u4E86 \u2713" });
    closeBtn.addClass("mod-cta");
    closeBtn.addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
  /**
   * 按来源分组任务
   */
  groupTasksBySource() {
    const groups = {
      daily: [],
      nike: [],
      holiday: [],
      recurring: []
    };
    for (const task of this.tasks) {
      if (groups[task.source]) {
        groups[task.source].push(task);
      }
    }
    return groups;
  }
  /**
   * 渲染待生成的周期任务区域
   */
  renderPendingSection(container) {
    if (this.pendingRecurringTasks.length === 0) {
      return;
    }
    const sectionEl = container.createDiv({ cls: "task-reminder-group task-reminder-pending" });
    const titleEl = sectionEl.createDiv({ cls: "task-reminder-group-title" });
    titleEl.setText(`\u{1F504} \u5F85\u751F\u6210 (${this.pendingRecurringTasks.length})`);
    for (const task of this.pendingRecurringTasks) {
      const itemEl = sectionEl.createDiv({ cls: "task-reminder-item task-pending-item" });
      const iconEl = itemEl.createSpan({ cls: "task-icon" });
      iconEl.setText("\u25CB");
      const textEl = itemEl.createSpan({ cls: "task-text task-pending-text" });
      textEl.setText(task.name);
      const typeEl = itemEl.createSpan({ cls: "task-type-label" });
      typeEl.setText(task.type);
    }
  }
  /**
   * 检查是否过期
   * 修复 P1-2：使用本地时间而非 UTC
   */
  isOverdue(dueDate) {
    const today = (0, import_obsidian8.moment)().format("YYYY-MM-DD");
    return dueDate < today;
  }
  /**
   * 导航到任务所在文件
   */
  async navigateToTask(task) {
    const file = this.app.vault.getAbstractFileByPath(task.filePath);
    if (file && file instanceof import_obsidian8.TFile) {
      const leaf = this.app.workspace.getLeaf(false);
      await leaf.openFile(file);
      if (task.line !== void 0) {
        setTimeout(() => {
          const view = leaf.view;
          if (view == null ? void 0 : view.editor) {
            const line = task.line;
            view.editor.setCursor({ line, ch: 0 });
            view.editor.scrollIntoView(
              { from: { line, ch: 0 }, to: { line, ch: 0 } },
              true
            );
          }
        }, 100);
      }
    }
    this.close();
  }
  /**
   * F6: 显示移动菜单
   */
  showMoveMenu(task, event) {
    const menu = new import_obsidian8.Menu();
    menu.addItem((item) => {
      item.setTitle("\u79FB\u52A8\u5230...").setIcon("calendar").onClick(() => {
        var _a;
        return (_a = this.onMoveTask) == null ? void 0 : _a.call(this, task);
      });
    });
    menu.showAtMouseEvent(event);
  }
  /**
   * F6: 设置移动端长按手势
   */
  setupLongPressGesture(itemEl, task) {
    let touchTimer = null;
    itemEl.addEventListener("touchstart", (e) => {
      touchTimer = window.setTimeout(() => {
        const touch = e.touches[0];
        const menu = new import_obsidian8.Menu();
        menu.addItem((item) => {
          item.setTitle("\u79FB\u52A8\u5230...").setIcon("calendar").onClick(() => {
            var _a;
            return (_a = this.onMoveTask) == null ? void 0 : _a.call(this, task);
          });
        });
        menu.showAtPosition({ x: touch.clientX, y: touch.clientY });
      }, 500);
    }, { passive: true });
    itemEl.addEventListener("touchend", () => {
      if (touchTimer) {
        window.clearTimeout(touchTimer);
        touchTimer = null;
      }
    });
    itemEl.addEventListener("touchmove", () => {
      if (touchTimer) {
        window.clearTimeout(touchTimer);
        touchTimer = null;
      }
    });
  }
};

// src/ui/QuickAddModal.ts
var import_obsidian10 = require("obsidian");

// src/ui/DatePickerModal.ts
var import_obsidian9 = require("obsidian");
var DatePickerModal = class extends import_obsidian9.Modal {
  constructor(app, options) {
    var _a;
    super(app);
    this.calendarContainer = null;
    /** 快捷选项（表驱动） */
    this.shortcuts = [
      { label: "\u4ECA\u5929", getDate: () => moment() },
      { label: "\u660E\u5929", getDate: () => moment().add(1, "day") },
      { label: "\u540E\u5929", getDate: () => moment().add(2, "days") },
      { label: "\u4E0B\u5468\u4E00", getDate: () => moment().day(8) },
      { label: "\u4E0B\u5468\u516D", getDate: () => moment().day(13) }
    ];
    this.options = options;
    this.selectedDate = ((_a = options.initialDate) == null ? void 0 : _a.clone()) || moment();
    this.currentMonth = this.selectedDate.clone();
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    this.modalEl.addClass("date-picker-modal");
    titleEl.setText(this.options.title || "\u9009\u62E9\u65E5\u671F");
    const quickOptions = contentEl.createDiv({ cls: "date-picker-quick-options" });
    for (const shortcut of this.shortcuts) {
      const btn = quickOptions.createEl("button", {
        text: shortcut.label,
        cls: "date-picker-shortcut-btn"
      });
      btn.addEventListener("click", () => this.selectDate(shortcut.getDate()));
    }
    this.calendarContainer = contentEl.createDiv({ cls: "date-picker-calendar" });
    this.renderCalendar();
    const inputContainer = contentEl.createDiv({ cls: "date-picker-input" });
    const inputLabel = inputContainer.createEl("label", { text: "\u5FEB\u901F\u8F93\u5165\uFF1A" });
    const input = inputContainer.createEl("input", {
      type: "text",
      placeholder: "+3 \u6216 2026-02-10",
      cls: "date-picker-text-input"
    });
    inputLabel.appendChild(input);
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        const parsed = this.parseInput(input.value);
        if (parsed) {
          this.selectDate(parsed);
        } else {
          new import_obsidian9.Notice("\u65E0\u6548\u7684\u65E5\u671F\u683C\u5F0F");
        }
      }
    });
    const btnContainer = contentEl.createDiv({ cls: "modal-button-container" });
    const cancelBtn = btnContainer.createEl("button", { text: "\u53D6\u6D88" });
    cancelBtn.addEventListener("click", () => {
      var _a, _b;
      (_b = (_a = this.options).onCancel) == null ? void 0 : _b.call(_a);
      this.close();
    });
    if (import_obsidian9.Platform.isMobile) {
      this.setupSwipeGestures();
    }
  }
  /**
   * 渲染日历网格
   */
  renderCalendar() {
    if (!this.calendarContainer) return;
    this.calendarContainer.empty();
    const nav = this.calendarContainer.createDiv({ cls: "calendar-nav" });
    const prevBtn = nav.createEl("button", {
      text: "\u25C0",
      cls: "calendar-nav-btn",
      attr: { "aria-label": "\u4E0A\u4E2A\u6708" }
    });
    prevBtn.addEventListener("click", () => {
      this.currentMonth.subtract(1, "month");
      this.renderCalendar();
    });
    const monthLabel = nav.createSpan({ cls: "calendar-month-label" });
    monthLabel.setText(this.currentMonth.format("YYYY\u5E74 M\u6708"));
    const nextBtn = nav.createEl("button", {
      text: "\u25B6",
      cls: "calendar-nav-btn",
      attr: { "aria-label": "\u4E0B\u4E2A\u6708" }
    });
    nextBtn.addEventListener("click", () => {
      this.currentMonth.add(1, "month");
      this.renderCalendar();
    });
    const weekHeader = this.calendarContainer.createDiv({ cls: "calendar-week-header" });
    const weekDays = ["\u4E00", "\u4E8C", "\u4E09", "\u56DB", "\u4E94", "\u516D", "\u65E5"];
    for (const day of weekDays) {
      weekHeader.createSpan({ text: day, cls: "calendar-week-day" });
    }
    const grid = this.calendarContainer.createDiv({ cls: "calendar-grid" });
    const startOfMonth = this.currentMonth.clone().startOf("month");
    const endOfMonth = this.currentMonth.clone().endOf("month");
    const startDay = startOfMonth.isoWeekday();
    for (let i = 1; i < startDay; i++) {
      grid.createDiv({ cls: "calendar-day empty" });
    }
    const today = moment().format("YYYY-MM-DD");
    const daysInMonth = endOfMonth.date();
    for (let d = 1; d <= daysInMonth; d++) {
      const date = this.currentMonth.clone().date(d);
      const dateStr = date.format("YYYY-MM-DD");
      const dayEl = grid.createDiv({
        cls: "calendar-day",
        text: String(d)
      });
      if (dateStr === today) {
        dayEl.addClass("is-today");
      }
      if (dateStr === this.selectedDate.format("YYYY-MM-DD")) {
        dayEl.addClass("is-selected");
      }
      if (dateStr < today && !this.options.allowPastDates) {
        dayEl.addClass("is-past");
      } else {
        dayEl.addEventListener("click", () => this.selectDate(date));
      }
    }
  }
  /**
   * 解析用户输入
   * 支持 +N 格式（如 +3 表示 3 天后）和 YYYY-MM-DD 格式
   */
  parseInput(value) {
    value = value.trim();
    if (value.startsWith("+")) {
      const days = parseInt(value.slice(1), 10);
      if (!isNaN(days) && days >= 0) {
        return moment().add(days, "days");
      }
    }
    const parsed = moment(value, "YYYY-MM-DD", true);
    if (parsed.isValid()) {
      if (!this.options.allowPastDates && parsed.isBefore(moment(), "day")) {
        new import_obsidian9.Notice("\u4E0D\u5141\u8BB8\u9009\u62E9\u8FC7\u53BB\u65E5\u671F");
        return null;
      }
      return parsed;
    }
    return null;
  }
  /**
   * 选择日期并关闭弹窗
   */
  selectDate(date) {
    if (!this.options.allowPastDates && date.isBefore(moment(), "day")) {
      new import_obsidian9.Notice("\u4E0D\u5141\u8BB8\u9009\u62E9\u8FC7\u53BB\u65E5\u671F");
      return;
    }
    this.options.onSelect(date);
    this.close();
  }
  /**
   * 设置移动端滑动手势
   */
  setupSwipeGestures() {
    if (!this.calendarContainer) return;
    let touchStartX = 0;
    let touchEndX = 0;
    this.calendarContainer.addEventListener("touchstart", (e) => {
      touchStartX = e.changedTouches[0].screenX;
    }, { passive: true });
    this.calendarContainer.addEventListener("touchend", (e) => {
      touchEndX = e.changedTouches[0].screenX;
      this.handleSwipe(touchStartX, touchEndX);
    }, { passive: true });
  }
  /**
   * 处理滑动手势
   */
  handleSwipe(startX, endX) {
    const threshold = 50;
    const diff = endX - startX;
    if (Math.abs(diff) < threshold) return;
    if (diff > 0) {
      this.currentMonth.subtract(1, "month");
    } else {
      this.currentMonth.add(1, "month");
    }
    this.renderCalendar();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/ui/QuickAddModal.ts
var QuickAddModal = class extends import_obsidian10.Modal {
  constructor(app, dailyNoteService, allowPastDates = false) {
    super(app);
    this.dailyNoteService = dailyNoteService;
    this.allowPastDates = allowPastDates;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    this.modalEl.addClass("quick-add-modal");
    titleEl.setText("\u2795 \u5FEB\u901F\u6DFB\u52A0 Todo");
    const inputContainer = contentEl.createDiv({ cls: "quick-add-input-container" });
    this.inputEl = inputContainer.createEl("input", {
      type: "text",
      placeholder: "\u8F93\u5165\u4EFB\u52A1\u5185\u5BB9...",
      cls: "quick-add-input"
    });
    this.inputEl.focus();
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        if (e.ctrlKey || e.metaKey) {
          this.addToDate((0, import_obsidian10.moment)());
        } else {
          this.openDatePicker();
        }
      }
    });
    const hintEl = contentEl.createDiv({ cls: "quick-add-hint" });
    hintEl.setText("\u63D0\u793A\uFF1A\u6309 Enter \u9009\u62E9\u65E5\u671F\uFF0CCtrl/Cmd+Enter \u76F4\u63A5\u6DFB\u52A0\u5230\u4ECA\u5929");
    const btnContainer = contentEl.createDiv({ cls: "modal-button-container" });
    const todayBtn = btnContainer.createEl("button", { text: "\u{1F4C5} \u4ECA\u5929" });
    todayBtn.addEventListener("click", () => this.addToDate((0, import_obsidian10.moment)()));
    const pickDateBtn = btnContainer.createEl("button", { text: "\u{1F5D3}\uFE0F \u9009\u62E9\u65E5\u671F..." });
    pickDateBtn.addClass("mod-cta");
    pickDateBtn.addEventListener("click", () => this.openDatePicker());
  }
  /**
   * 打开日期选择器
   */
  openDatePicker() {
    const content = this.inputEl.value.trim();
    if (!content) {
      new import_obsidian10.Notice("\u8BF7\u8F93\u5165\u4EFB\u52A1\u5185\u5BB9");
      this.inputEl.focus();
      return;
    }
    new DatePickerModal(this.app, {
      title: "\u9009\u62E9\u76EE\u6807\u65E5\u671F",
      allowPastDates: this.allowPastDates,
      onSelect: (date) => this.addToDate(date)
    }).open();
  }
  /**
   * 添加任务到指定日期
   */
  async addToDate(date) {
    const content = this.inputEl.value.trim();
    if (!content) {
      new import_obsidian10.Notice("\u8BF7\u8F93\u5165\u4EFB\u52A1\u5185\u5BB9");
      this.inputEl.focus();
      return;
    }
    try {
      await this.dailyNoteService.writeTask(content, date);
      new import_obsidian10.Notice(`\u2705 \u5DF2\u6DFB\u52A0\u5230 ${date.format("YYYY-MM-DD")}`);
      this.inputEl.value = "";
      this.inputEl.focus();
    } catch (e) {
      new import_obsidian10.Notice(`\u274C \u6DFB\u52A0\u5931\u8D25: ${e.message}`);
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/ui/StatusBarItem.ts
var StatusBarItem = class {
  constructor(app, element, dataService, onClick) {
    this.app = app;
    this.element = element;
    this.dataService = dataService;
    this.onClick = onClick;
    this.setup();
  }
  /**
   * 初始化状态栏项
   */
  setup() {
    this.element.addClass("task-reminder-status");
    this.element.setText("\u{1F4CB} ...");
    this.element.setAttribute("aria-label", "\u52A0\u8F7D\u4E2D...");
    this.element.onClickEvent(() => {
      this.onClick();
    });
  }
  /**
   * 更新显示
   */
  async update() {
    var _a, _b, _c;
    const dvApi = (_c = (_b = (_a = this.app.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b.dataview) == null ? void 0 : _c.api;
    if (!dvApi) {
      this.element.setText("\u{1F4CB} ?");
      this.element.setAttribute("aria-label", "\u9700\u8981 Dataview \u63D2\u4EF6");
      return;
    }
    try {
      const count = await this.dataService.getTaskCount();
      this.element.setText(`\u{1F4CB} ${count}`);
      this.element.setAttribute("aria-label", `\u4ECA\u65E5\u5F85\u529E: ${count} \u9879`);
      this.element.removeClass("has-tasks", "no-tasks");
      if (count > 0) {
        this.element.addClass("has-tasks");
      } else {
        this.element.addClass("no-tasks");
      }
    } catch (e) {
      console.error("[TaskReminder] Status bar update failed:", e);
      this.element.setText("\u{1F4CB} !");
      this.element.setAttribute("aria-label", "\u83B7\u53D6\u4EFB\u52A1\u5931\u8D25");
    }
  }
  /**
   * 设置加载状态
   */
  setLoading() {
    this.element.setText("\u{1F4CB} ...");
    this.element.setAttribute("aria-label", "\u52A0\u8F7D\u4E2D...");
  }
};

// src/main.ts
var TaskReminderPlugin = class extends import_obsidian11.Plugin {
  constructor() {
    super(...arguments);
    this.statusBarItem = null;
    this.statusBarEl = null;
    this.refreshDebounceTimer = null;
    this.refreshIntervalId = null;
  }
  async onload() {
    console.log("[TaskReminder] Loading plugin...");
    await this.loadSettings();
    this.dataService = new TaskDataService(this.app, this.settings);
    this.dailyNoteService = new DailyNoteService(this.app, this.settings);
    this.taskMoveService = new TaskMoveService(this.app, this.dailyNoteService, this.settings);
    this.addSettingTab(new TaskReminderSettingTab(this.app, this));
    this.addCommand({
      id: "show-task-reminder",
      name: "Show today's task reminder",
      callback: () => this.showReminder(true)
      // force = true, 不写入已弹过标记
    });
    this.addCommand({
      id: "quick-add-todo",
      name: "Quick add todo",
      callback: () => this.openQuickAdd()
    });
    this.addRibbonIcon("plus-circle", "Quick add todo", () => {
      this.openQuickAdd();
    });
    this.addCommand({
      id: "move-current-task",
      name: "Move current line task to another date",
      editorCallback: (editor) => this.moveCurrentLineTask(editor)
    });
    if (this.settings.showStatusBar && import_obsidian11.Platform.isDesktop) {
      this.setupStatusBar();
    }
    this.app.workspace.onLayoutReady(() => {
      this.scheduleReminder();
    });
    console.log("[TaskReminder] Plugin loaded successfully");
  }
  /**
   * 设置状态栏
   */
  setupStatusBar() {
    this.statusBarEl = this.addStatusBarItem();
    this.statusBarItem = new StatusBarItem(
      this.app,
      this.statusBarEl,
      this.dataService,
      () => this.showReminder(true)
    );
    this.updateStatusBar();
    this.refreshIntervalId = window.setInterval(
      () => this.updateStatusBar(),
      5 * 60 * 1e3
    );
    this.registerInterval(this.refreshIntervalId);
    this.registerEvent(
      this.app.vault.on("modify", () => this.debouncedRefresh())
    );
  }
  /**
   * 防抖刷新
   */
  debouncedRefresh() {
    if (this.refreshDebounceTimer) {
      window.clearTimeout(this.refreshDebounceTimer);
    }
    this.refreshDebounceTimer = window.setTimeout(() => {
      this.dataService.invalidateCache();
      this.updateStatusBar();
    }, 500);
  }
  /**
   * 更新状态栏
   */
  async updateStatusBar() {
    if (this.statusBarItem) {
      await this.statusBarItem.update();
    }
  }
  /**
   * 调度提醒
   */
  scheduleReminder() {
    if (!this.settings.enabled) {
      console.log("[TaskReminder] Auto reminder disabled");
      return;
    }
    const todayStr = (0, import_obsidian11.moment)().format("YYYY-MM-DD");
    if (this.settings.lastReminderDate === todayStr) {
      console.log("[TaskReminder] Already shown today, skipping");
      return;
    }
    console.log(`[TaskReminder] Scheduling reminder in ${this.settings.popupDelay / 1e3}s`);
    window.setTimeout(() => {
      this.showReminder(false);
    }, this.settings.popupDelay);
  }
  /**
   * 显示提醒
   * @param force 是否强制显示（忽略"已弹过"状态）
   */
  async showReminder(force) {
    if (!this.checkDataviewReady()) {
      return;
    }
    console.log("[TaskReminder] Fetching task data...");
    const result = await this.dataService.getTaskData();
    const pendingRecurringTasks = await this.dataService.getPendingRecurringTasks();
    result.errors.forEach((err) => {
      if (!err.recoverable) {
        new import_obsidian11.Notice(`Task Reminder: ${err.source} - ${err.message}`, 5e3);
      }
    });
    console.log(`[TaskReminder] Found ${result.tasks.length} tasks, ${pendingRecurringTasks.length} pending recurring`);
    const hasTasks = result.tasks.length > 0 || pendingRecurringTasks.length > 0;
    if (hasTasks) {
      if (!force) {
        this.settings.lastReminderDate = (0, import_obsidian11.moment)().format("YYYY-MM-DD");
        await this.saveSettings();
        console.log("[TaskReminder] Marked as shown for today");
      }
      if (this.settings.reminderStyle === "both" || this.settings.reminderStyle === "notice") {
        const taskMsg = result.tasks.length > 0 ? `${result.tasks.length} \u4E2A\u5F85\u529E\u4EFB\u52A1` : "";
        const pendingMsg = pendingRecurringTasks.length > 0 ? `${pendingRecurringTasks.length} \u4E2A\u5F85\u751F\u6210` : "";
        const msg = [taskMsg, pendingMsg].filter(Boolean).join(", ");
        new import_obsidian11.Notice(`\u23F0 \u4ECA\u65E5\u6709 ${msg}!`, this.settings.popupDuration);
      }
      if (this.settings.reminderStyle === "both" || this.settings.reminderStyle === "modal") {
        new ReminderModal(
          this.app,
          result.tasks,
          pendingRecurringTasks,
          (tasks) => this.generateRecurringTasks(tasks),
          (task) => this.handleMoveTask(task)
          // F6: 移动任务回调
        ).open();
      }
    } else {
      console.log("[TaskReminder] No tasks found, not recording as shown");
      if (force) {
        new import_obsidian11.Notice("\u2705 \u4ECA\u65E5\u6CA1\u6709\u5F85\u529E\u4EFB\u52A1!", 3e3);
      }
    }
  }
  /**
   * 生成周期任务到 Daily Note（F4 功能）
   */
  async generateRecurringTasks(tasks) {
    const count = await this.dailyNoteService.writeRecurringTasks(tasks);
    this.dataService.invalidateCache();
    await this.updateStatusBar();
    return count;
  }
  /**
   * F5: 打开快速添加弹窗
   */
  openQuickAdd() {
    if (!this.dailyNoteService.isDailyNotePathConfigured()) {
      new import_obsidian11.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E Daily Note \u8DEF\u5F84");
      return;
    }
    new QuickAddModal(this.app, this.dailyNoteService, this.settings.allowMoveToPast).open();
  }
  /**
   * F6: 处理任务移动
   */
  handleMoveTask(task) {
    const checkResult = this.taskMoveService.canMoveTask(task);
    if (!checkResult.canMove) {
      new import_obsidian11.Notice(`\u274C ${checkResult.reason}`);
      return;
    }
    this.openMoveTaskDatePicker(task);
  }
  /**
   * F6: 移动当前行任务（Command Palette 命令）
   */
  moveCurrentLineTask(editor) {
    var _a;
    if (!this.dailyNoteService.isDailyNotePathConfigured()) {
      new import_obsidian11.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E Daily Note \u8DEF\u5F84");
      return;
    }
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian11.Notice("\u274C \u6CA1\u6709\u6253\u5F00\u7684\u6587\u4EF6");
      return;
    }
    const dailyPath = ((_a = this.settings.dailyNotePath) == null ? void 0 : _a.trim()) || "";
    if (!activeFile.path.startsWith(dailyPath)) {
      new import_obsidian11.Notice("\u274C \u4EC5\u652F\u6301\u79FB\u52A8 Daily Note \u4E2D\u7684\u4EFB\u52A1");
      return;
    }
    const cursor = editor.getCursor();
    const lineNumber = cursor.line;
    const lineText = editor.getLine(lineNumber);
    if (!lineText.match(/^\s*- \[ \]/)) {
      new import_obsidian11.Notice("\u274C \u5F53\u524D\u884C\u4E0D\u662F\u672A\u5B8C\u6210\u7684\u4EFB\u52A1");
      return;
    }
    const task = {
      text: lineText.replace(/^\s*- \[ \]\s*/, ""),
      fullText: lineText,
      filePath: activeFile.path,
      line: lineNumber,
      source: "daily",
      sourceLabel: "Daily Note",
      isMeeting: false
    };
    this.openMoveTaskDatePicker(task);
  }
  /**
   * F6: 打开移动任务日期选择器
   */
  openMoveTaskDatePicker(task) {
    new DatePickerModal(this.app, {
      title: "\u79FB\u52A8\u4EFB\u52A1\u5230",
      allowPastDates: this.settings.allowMoveToPast,
      onSelect: async (date) => {
        try {
          const result = await this.taskMoveService.moveTask(task, date);
          if (result.success) {
            new import_obsidian11.Notice(`\u2705 \u5DF2\u79FB\u52A8\u5230 ${date.format("YYYY-MM-DD")}`);
            this.dataService.invalidateCache();
            await this.updateStatusBar();
          }
          if (result.error) {
            new import_obsidian11.Notice(`\u26A0\uFE0F ${result.error}`, 8e3);
          }
        } catch (e) {
          new import_obsidian11.Notice(`\u274C \u79FB\u52A8\u5931\u8D25: ${e.message}`);
        }
      }
    }).open();
  }
  /**
   * 检查 Dataview 是否就绪
   */
  checkDataviewReady() {
    var _a, _b, _c;
    const dv = (_c = (_b = (_a = this.app.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b.dataview) == null ? void 0 : _c.api;
    if (!dv) {
      new import_obsidian11.Notice("Task Reminder: \u9700\u8981\u5B89\u88C5\u5E76\u542F\u7528 Dataview \u63D2\u4EF6", 5e3);
      return false;
    }
    return true;
  }
  /**
   * 加载设置
   */
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  /**
   * 保存设置
   */
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.dataService) {
      this.dataService.updateSettings(this.settings);
    }
    if (this.dailyNoteService) {
      this.dailyNoteService.updateSettings(this.settings);
    }
    if (this.taskMoveService) {
      this.taskMoveService.updateSettings(this.settings);
    }
  }
  onunload() {
    console.log("[TaskReminder] Unloading plugin...");
    if (this.refreshDebounceTimer) {
      window.clearTimeout(this.refreshDebounceTimer);
    }
    console.log("[TaskReminder] Plugin unloaded");
  }
};
